import path from 'node:path'
import type { ResolvedConfig } from 'vite'
import fg from 'fast-glob'
import fs from 'fs-extra'

export type VitePluginMetaEnvTypeOptions = {
  envFile?: string[] | string
  outFile?: string
}

export function vitePluginMetaEnvType({
  envFile = ['*.env', '.env.*', '.env'],
  outFile = 'vite-meta-env.d.ts'
}: VitePluginMetaEnvTypeOptions = {}) {
  return {
    name: 'meta-env-type-plugin',
    configResolved(config: ResolvedConfig) {
      const root = config.root || process.cwd()
      const envFiles = fg.globSync(envFile)

      const envVars: Record<string, string> = {}

      envFiles.forEach((file) => {
        const filePath = path.resolve(root, file)
        if (fs.existsSync(filePath)) {
          const content = fs.readFileSync(filePath, 'utf8')
          const lines = content.split('\n')

          lines.forEach((line) => {
            const trimmedLine = line.trim()
            if (trimmedLine && !trimmedLine.startsWith('#')) {
              const [key, value] = trimmedLine.split('=')
              if (key) {
                envVars[key] = value || ''
              }
            }
          })
        }
      })

      const typeDefs = generateTypeDefs(envVars)
      const outputPath = path.resolve(root, outFile)
      fs.ensureFileSync(outputPath)
      fs.writeFileSync(outputPath, typeDefs)
    }
  }
}

function generateTypeDefs(envVars: Record<string, string>): string {
  const envProperties = Object.entries(envVars)
    .map(([key, value]) => {
      return `  readonly ${key}: string`
    })
    .join('\n')

  return `// generated by meta-env-type-plugin
/// <reference types="vite/client" />

interface ImportMetaEnv {
${envProperties}
}
`
}
